name: smart_gpt
description: "A Smart AI Assistant"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  flutter:
    sdk: flutter

  # UI
  animated_text_kit: ^4.2.2
  ionicons: ^0.2.2
  markdown_viewer: ^0.6.2

  # Data Persistence
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking and Models
  dio: ^5.4.3+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Auth
  auth0_flutter: ^1.7.2

  # Misc
  envied: ^0.5.4+1
  intl: ^0.19.0

dev_dependencies:
  # Linting
  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.10
  envied_generator: ^0.5.4+1
  freezed: ^2.5.2
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
